

alter table DCFUM_Keycloak.dcf_sec_role_taskgrp add role_id varchar2(36);

-- table DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP altered.

ALTER TABLE DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP
ADD CONSTRAINT FK_ROLEID
FOREIGN KEY (ROLE_ID)
REFERENCES DCFUM_Keycloak.KEYCLOAK_ROLE (ID);

-- table DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP altered.

UPDATE DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP SET ROLE_ID = (SELECT ID FROM DCFUM_Keycloak.KEYCLOAK_ROLE WHERE NAME='BRANCHROLE') WHERE STRROLE='BRANCHROLE'; 
UPDATE DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP SET ROLE_ID = (SELECT ID FROM DCFUM_Keycloak.KEYCLOAK_ROLE WHERE NAME='HOROLE') WHERE STRROLE='HOROLE'; 
UPDATE DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP SET ROLE_ID = (SELECT ID FROM DCFUM_Keycloak.KEYCLOAK_ROLE WHERE NAME='TRAINEE') WHERE STRROLE='TRAINEE'; 
UPDATE DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP SET ROLE_ID = (SELECT ID FROM DCFUM_Keycloak.KEYCLOAK_ROLE WHERE NAME='TRAINEESUPERVISOR') WHERE STRROLE='TRAINEESUPERVISOR'; 
UPDATE DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP SET ROLE_ID = (SELECT ID FROM DCFUM_Keycloak.KEYCLOAK_ROLE WHERE NAME='TRAINER') WHERE STRROLE='TRAINER'; 
UPDATE DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP SET ROLE_ID = (SELECT ID FROM DCFUM_Keycloak.KEYCLOAK_ROLE WHERE NAME='TRAININGCREAOR') WHERE STRROLE='TRAININGCREAOR'; 
UPDATE DCFUM_Keycloak.DCF_SEC_ROLE_TASKGRP SET ROLE_ID = (SELECT ID FROM DCFUM_Keycloak.KEYCLOAK_ROLE WHERE NAME='TRAININGSUPERVISOR') WHERE STRROLE='TRAININGSUPERVISOR'; 

/*
95 rows updated.
102 rows updated.
1 rows updated.
1 rows updated.
1 rows updated.
1 rows updated.
1 rows updated.
*/